Repository kubevirt/containerdisks, pull requests merged in 2022-05, with the labels that each got.

#33 Add fedora:36 to the artifacts
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note, lgtm, approved, size/XS

#34 Update UseForDocs flags of artifacts
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#36 Add UseForLatest attribute to common.Registry entries
  cmd/medius/common/registry.go
  cmd/medius/images/common.go
  cmd/medius/images/promote.go
  cmd/medius/images/push.go
  cmd/medius/images/verify.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#38 Adding additional approvers
  OWNERS
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#40 Filter out Fedora versions lower than 35
  artifacts/fedora/fedora.go
  artifacts/fedora/fedora_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved
