Repository kubevirt/containerdisks, pull requests merged in 2022-04, with the labels that each got.

#18 Add images verify cmd
  .gitignore
  .golangci.yml
  Makefile
  artifacts/centos/centos.go
  artifacts/centos/centos_test.go
  artifacts/centosstream/centos-stream.go
  artifacts/centosstream/centos-stream_test.go
  artifacts/fedora/fedora.go
  artifacts/fedora/fedora_test.go
  artifacts/generic/generic.go
  artifacts/rhcos/rhcos.go
  artifacts/rhcos/rhcos_test.go
  artifacts/rhcosprerelease/rhcos.go
  artifacts/rhcosprerelease/rhcos_test.go
  cmd/medius/common/options.go
  cmd/medius/docs/docs.go
  cmd/medius/images/common.go
  cmd/medius/images/push.go
  cmd/medius/images/verify.go
  cmd/medius/main.go
  go.mod
  go.sum
  pkg/api/artifact.go
  pkg/build/build.go
  pkg/build/tar.go
  pkg/build/tar_test.go
  pkg/docs/data/cloudinit.tpl
  pkg/docs/data/cloudinit.txt
  pkg/docs/data/description.tpl
  pkg/docs/data/ignition.tpl
  pkg/docs/data/ignition.txt
  pkg/docs/docs.go
  pkg/http/http.go
  pkg/repository/repository.go
  pkg/tests/common.go
  pkg/tests/guestosinfo.go
  pkg/tests/ssh.go
Labels: dco-signoff: yes, release-note, lgtm, size/XXL, approved

#22 add 4.11 pre-release images
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#21 Add images promote cmd
  cmd/medius/common/options.go
  cmd/medius/images/common.go
  cmd/medius/images/promote.go
  cmd/medius/images/push.go
  cmd/medius/images/verify.go
  cmd/medius/main.go
  pkg/api/artifact.go
  pkg/repository/repository.go
Labels: dco-signoff: yes, release-note, lgtm, size/L, approved

#20 Add --[source|target]-registry flags to images push cmd
  cmd/medius/common/options.go
  cmd/medius/docs/docs.go
  cmd/medius/images/push.go
  cmd/medius/images/verify.go
  cmd/medius/main.go
Labels: dco-signoff: yes, size/M, release-note, lgtm, approved

#23 Add --no-fail flag to images [push|verify]
  cmd/medius/common/options.go
  cmd/medius/images/push.go
  cmd/medius/images/verify.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#24 Pipeline for testing based on cirros
  cmd/medius/images/verify.go
  pipeline.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#25 Pipeline for the periodic job
  pipeline-periodic.sh
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#26 Fix README typos
  README.md
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#27 Add Ubuntu LTS versions
  artifacts/ubuntu/testdata/SHA256SUM
  artifacts/ubuntu/ubuntu.go
  artifacts/ubuntu/ubuntu_test.go
  cmd/medius/common/registry.go
  pkg/hashsum/hashsum.go
Labels: dco-signoff: yes, release-note, lgtm, size/L, approved

#28 Increase wait timeout for kubevirtci
  hack/kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#29 Don't add shasum tags to ubuntu
  artifacts/ubuntu/ubuntu.go
  artifacts/ubuntu/ubuntu_test.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#30 Fix invalid URL
  README.md
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#31 Push containerdisks docs if a quay oauth token is present
  pipeline-periodic.sh
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS
