Repository kubevirt/containerdisks, pull requests merged in 2024-04, with the labels that each got.

#93 registry: Bump default instance type env variables
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note-none, size/S, lgtm, approved

#92 registry: Remove CentOS 8.4 and Ubuntu 18.04
  artifacts/centos/centos.go
  artifacts/centos/centos_test.go
  artifacts/centos/testdata/centos8.checksum
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note-none, lgtm, size/L, approved

#84 feat: add arm64 artifacts
  artifacts/centos/centos_test.go
  artifacts/centosstream/centos-stream.go
  artifacts/centosstream/centos-stream_test.go
  artifacts/centosstream/testdata/centos-stream8-aarch64.checksum
  artifacts/centosstream/testdata/centos-stream8-x86_64.checksum
  artifacts/centosstream/testdata/centos-stream9-aarch64.checksum
  artifacts/centosstream/testdata/centos-stream9-x86_64.checksum
  artifacts/fedora/fedora.go
  artifacts/fedora/fedora_test.go
  artifacts/fedora/testdata/releases.json
  artifacts/ubuntu/ubuntu.go
  artifacts/ubuntu/ubuntu_test.go
  cmd/medius/common/registry.go
  pkg/architecture/arch.go
Labels: dco-signoff: yes, release-note, lgtm, size/XXL, approved

#100 Set containerdisks' entrypoint to "no-entrypoint"
  pkg/build/build.go
Labels: dco-signoff: yes, release-note, size/S, lgtm, approved

#104 Bump golang version and k8s.io/apimachinery
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/api/resource/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/api/validation/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/runtime/helper.go
  vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/intstr/generated.pb.go
  vendor/k8s.io/apimachinery/pkg/util/managedfields/node.yaml
  vendor/k8s.io/apimachinery/pkg/util/sets/doc.go
  vendor/k8s.io/apimachinery/pkg/util/sets/ordered.go
  vendor/k8s.io/apimachinery/pkg/util/sets/set.go
  vendor/k8s.io/apimachinery/pkg/util/validation/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XL, lgtm, approved
