Repository kubevirt/containerdisks, pull requests merged in 2024-11, with the labels that each got.

#217 kubevirtci: Fix paths to cluster-up scripts
  hack/kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#218 Bump golang 1.22.9
  go.mod
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#203 Add s390x for ubuntu and centos artifacts
  Makefile
  artifacts/centosstream/centos-stream_test.go
  artifacts/centosstream/testdata/centos-stream9-s390x.checksum
  artifacts/ubuntu/ubuntu_test.go
  cmd/medius/common/registry.go
  cmd/medius/images/push.go
  pkg/architecture/arch.go
  pkg/repository/repository.go
Labels: dco-signoff: yes, release-note, lgtm, size/L, approved

#224 Add s390x support for Fedora artifact
  artifacts/fedora/fedora.go
  artifacts/fedora/fedora_test.go
  artifacts/fedora/testdata/releases.json
Labels: dco-signoff: yes, release-note, lgtm, size/L, approved

#227 feat(containerdisk): Add CentOS Stream 10 containerdisk
  artifacts/centosstream/centos-stream.go
  artifacts/centosstream/centos-stream_test.go
  artifacts/centosstream/testdata/centos-stream10-aarch64.checksum
  artifacts/centosstream/testdata/centos-stream10-s390x.checksum
  artifacts/centosstream/testdata/centos-stream10-x86_64.checksum
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note, lgtm, size/L, approved

#229 feat(centos): Remove CentOS Stream 8 support
  artifacts/centosstream/centos-stream.go
Labels: dco-signoff: yes, release-note, lgtm, approved, size/XS
