Repository kubevirt/containerdisks, pull requests merged in 2025-03, with the labels that each got.

#284 fix: disable Fedora 40 for s390x
  artifacts/fedora/fedora.go
  artifacts/fedora/fedora_test.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#305 Bump golang to 1.24.1
  Makefile
  go.mod
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#303 feat(containerdisk): Add support for Debian containerdisk and sha512 checksums
  artifacts/centosstream/centos-stream.go
  artifacts/centosstream/centos-stream_test.go
  artifacts/debian/debian.go
  artifacts/debian/debian_test.go
  artifacts/debian/testdata/debian-11-genericcloud-amd64.json
  artifacts/debian/testdata/debian-11-genericcloud-arm64.json
  artifacts/debian/testdata/debian-12-genericcloud-amd64.json
  artifacts/debian/testdata/debian-12-genericcloud-arm64.json
  artifacts/fedora/fedora.go
  artifacts/fedora/fedora_test.go
  artifacts/opensuse/leap/leap.go
  artifacts/opensuse/leap/leap_test.go
  artifacts/opensuse/tumbleweed/tumbleweed.go
  artifacts/opensuse/tumbleweed/tumbleweed_test.go
  artifacts/ubuntu/ubuntu.go
  artifacts/ubuntu/ubuntu_test.go
  cmd/medius/common/registry.go
  cmd/medius/images/push.go
  pkg/api/artifact.go
  pkg/http/http.go
  testutil/mockgetter.go
Labels: dco-signoff: yes, release-note, lgtm, size/XXL, approved

#308 chore(debian): Apply `latest` tag to Debian 12
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, release-note-none, lgtm, approved, size/XS

#309 chore(debian): Add `debian` preference and instancetype to Debian containerdisks
  artifacts/debian/debian_test.go
  cmd/medius/common/registry.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#296 feat: Add target architecture as a parameter for verification.
  cmd/medius/common/options.go
  cmd/medius/images/verify.go
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved

#315 chore(README): Add debian and improvements
  README.md
Labels: dco-signoff: yes, size/M, release-note-none, lgtm, approved
